#!/bin/bash
# POSIX

attach=0

while :; do
    case $1 in
        -a|-\?|--attach)
            attach=1
            ;;
        -?*)
            printf 'Warning: Unknown option: %s\n' "$1" >&2
            ;;
        *) #default case: no more options
            break
    esac

    shift
done

./mktestenvconfig || exit 1
. testenv_config

if [ "$attach" -eq "0" ]; then
    docker rm snow_test 2> /dev/null
    if [ $? -ne 0 ]; then
        printf 'Container already exists. Trying to attach...\n'
        docker exec -it --privileged snow_test /bin/bash 2> /dev/null
        if [ $? -ne 0 ]; then
            printf 'Creating new container.\n'
            docker run --name snow_test -p 8080:8080 -p 8000:8000 -p 6060:6060 \
            -p 8443:8443 \
            -it  -v ${SNOWFLAKE_REPO}:/go/src/snowflake -v \
            ${SNOWFLAKEWEB_REPO}:/go/src/snowflake-webext \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined snowbox \
            /bin/bash
        fi
        exit
    else 
        docker run --name snow_test -p 8080:8080 -p 8000:8000 -p 6060:6060 \
        -p 8443:8443 \
        -it -v ${SNOWFLAKE_REPO}:/go/src/snowflake -v \
        ${SNOWFLAKEWEB_REPO}:/go/src/snowflake-webext \
        --cap-add=SYS_PTRACE --security-opt seccomp=unconfined snowbox \
        /bin/bash
        exit
    fi
fi

docker exec -it snow_test /bin/bash
